### ISSUE TITLE
Ant-Man and the Wasp: Quantumania (released 2023-02-17) is not in any of the lists

### ISSUE THREAD

**Issue by AmperAndSand** [ThatGuySam/marvelorder#1]
_Ant-Man and the Wasp: Quantumania_ was released on February 17th, 2023, but it does not appear on either the "Universe Timeline" or "Upcoming" lists.

**Comment by ThatGuySam** [comment]
Oh, that's weird. 

I'll put it on my list to look into.

**Comment by ThatGuySam** [comment]
@AmperAndSand Should be showing up now. Feel free to let me know if it's still not there or if you find any other issues. 

https://marvelorder.com
https://marvelorder.com/en/ant-man-and-the-wasp-quantumania-640146/

<img width="1840" alt="Screenshot 2023-07-04 at 3 23 03 PM" src="https://github.com/ThatGuySam/marvelorder/assets/2830379/adbe8799-1f29-4182-8f68-398a20df5385">
